# Automatically synchronises the Nbody6PPGPU-ML branch with the stable branch
# 
# In case of failure (merge conflict) the conflict needs to be resolved by
# hand. For a detailed description see the git book:
#  git book: https://git-scm.com/book/en/v2
#  merge conflicts basics: https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging
#  advanced merging: https://git-scm.com/book/en/v2/Git-Tools-Advanced-Merging
#
# The general outline goes as follows:
# 1. Make sure the stable and Nbody6PPGPU-ML branches are up to date, respectively
#    git checkout stable
#    git pull
#    git checkout Nbody6PPGPU-ML
#    git pull
# 2. Merge stable into Nbody6PPGPU-ML (make sure you are on the Nbody6PPGPU-ML branch first)
#    git checkout Nbody6PPGPU-ML
#    git merge stable
# 3. Merge conflicts should appear. Fix conflict in a way of your choice, e.g.,
#    git mergetool --tool=vimdiff
# 4. commit and push your changes to the upstream Nbody6PPGPU-ML branch
#    git push origin Nbody6PPGPU-ML

name: Synchronise Nbody6PPGPU-ML with dev branch

on:
  push:
    branches: [dev]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Setup GitHub Action User
        run: |
          git config user.name "GitHub Action"
          git config user.email "<EMAIL>"
      

      - name: Update Nbody6PPGPU-ML Branch
        run: |
          git fetch origin
          git checkout Nbody6PPGPU-ML
          git pull
          git merge origin/dev
          git push origin Nbody6PPGPU-ML
